title: Ika Sugita # your name (or website title) here
logo: "/images/fp.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Saya seorang Mahasiswi aktif tingkat akhir pada Program Studi Teknik Industri di Universitas Pamulang. Saya juga aktif berorganisasi dan suka bersosialisasi dengan semua kalangan masyarakat. Saya termasuk ke dalam orang-orang yang suka bernyanyi dan menulis. 
  <br><br>
  <a href="https://www.linkedin.com/in/ika-sugita-3922b1198/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
